### ISSUE TITLE
容器启动和访问报错

### ISSUE THREAD

**Issue by VectorHo** [lijiapengsa/lepus#1]
![image](https://user-images.githubusercontent.com/7578264/30730345-f3063842-9f2b-11e7-99c5-b8aea563b4ef.png)
![image](https://user-images.githubusercontent.com/7578264/30730351-044c288c-9f2c-11e7-88e5-3c2d6eb17f64.png)

**Comment by showniu** [comment]
Error message?

**Comment by showniu** [comment]
我看不到图，看不到错误消息

**Comment by showniu** [comment]
core/loader.php的346行、看一眼是什么配置
时间太久了、我先close掉、有问题再从新提 @VectorHo
