### ISSUE TITLE
访问报错，麻烦解答一下，

### ISSUE THREAD

**Issue by Lynn8023** [lijiapengsa/lepus#2]
![1111](https://user-images.githubusercontent.com/33685600/32828595-7e4c6d58-ca2a-11e7-9413-cf429874e021.png)

**Comment by Lynn8023** [comment]
A Database Error Occurred

Unable to select the specified database: lepus

Filename: core/Loader.php

Line Number: 346

**Comment by showniu** [comment]
请参考[issues1](https://github.com/lijiapengsa/lepus/issues/1)

**Comment by fdys1983** [comment]
我也经常报着个错误，刷新一下就好了，用着用着点别的页面的时候就出来了，但是主要是没准什么时候他就出来，很火大啊~~~
我已经放弃用高版本的php，mysql等内容，nginx也放弃了，用的是作者发的xampp的同样版本号的安装包

**Comment by showniu** [comment]
运维一个、一直没时间再搞这个...

**Comment by heguowei-stack** [comment]
/var/www/html/application/config/database.php这个文件里面的数据库账号密码好像没有配置，配置好之后重启一下就可以了。

**Comment by showniu** [comment]
下决心！！！ 这次一定抽时间搞它！！！
