### ISSUE TITLE
关于启动报错

### ISSUE THREAD

**Issue by immarktube** [lijiapengsa/lepus#3]
lepus server start fail!

报错信息只有这个，我在百度搜了一下别人都会有日志，我却没有。去教程检查了一遍，没发现少装了什么。。

**Comment by immarktube** [comment]
and  官网教程里 安装数据库连接Python的驱动包 里给的CDN已经404了，所以安装这个驱动包安不了

**Comment by immarktube** [comment]
我已经成功启动了，但是那个CDN地址还是无法访问，烦请修复，谢谢！

**Comment by showniu** [comment]
兄弟、你说是那个CDN地址？
