### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 853486395** [lijiapengsa/lepus#4]
![image](https://user-images.githubusercontent.com/5416583/57211355-8d11ff80-7012-11e9-89ac-e7d4f7ab349e.png)

**Comment by showniu** [comment]
是否已经配置数据库、并且数据库是否正常

**Comment by showniu** [comment]
请参考 [issues1](https://github.com/lijiapengsa/lepus/issues/1)
有时间我再重新在整理一下这个
