### ISSUE TITLE
快速启动多次,都是这个错误,镜像有问题呀!!

### ISSUE THREAD

**Issue by zhaowengxing** [lijiapengsa/lepus#5]
A Database Error Occurred

Unable to select the specified database: lepus

Filename: core/Loader.php

Line Number: 346

**Comment by showniu** [comment]
非常感谢您的关注、这个周末我会解决这个问题

**Comment by alterem** [comment]
那个，哥们儿，几年过去了，还没有周末吗？

**Comment by showniu** [comment]
Can't wait. Let's start now.

**Comment by showniu** [comment]
> 那个，哥们儿，几年过去了，还没有周末吗？

感谢兄弟的关注、因为系统和软件已经太久远了。所以Dockerfile已经无法修复了。尽管如此、我早README里面已经给出了修复方法。你可以尝试一下。我已经经过测试了。

**Comment by showniu** [comment]
已经在images中修复、并提交
